# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  api_server:
    image: furyhawk/listen:latest
    restart: always
    # depends_on:
    #   - postgres_db
    environment:
      DATABASE__HOSTNAME: ${DATABASE__HOSTNAME}
      DATABASE__USERNAME: ${DATABASE__USERNAME}
      DATABASE__PASSWORD: ${DATABASE__PASSWORD}
      DATABASE__PORT: ${DATABASE__PORT}
      DATABASE__DB: ${DATABASE__DB}
      SECURITY__JWT_SECRET_KEY: ${SECURITY__JWT_SECRET_KEY}
      SECURITY__BACKEND_CORS_ORIGINS: ${SECURITY__BACKEND_CORS_ORIGINS}
      SECURITY__ALLOWED_HOSTS: ${SECURITY__ALLOWED_HOSTS}
    ports:
      - "8000:8000"

  # postgres_db:
  #   restart: unless-stopped
  #   image: postgres:16
  #   volumes:
  #     - postgres_db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${DATABASE__DB}
  #     - POSTGRES_USER=${DATABASE__USERNAME}
  #     - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
  #   env_file:
  #     - .env
  #   ports:
  #     - "${DATABASE__PORT}:5432"

# volumes:
#   postgres_db:
