"""create_pressure_model

Revision ID: 670c74d20f60
Revises: 3f4082b6f747
Create Date: 2024-05-04 15:28:09.647774

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "670c74d20f60"
down_revision = "3f4082b6f747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "humidity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("humidity", sa.String(length=6), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pressure",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("pressure", sa.String(length=10), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pressure")
    op.drop_table("humidity")
    # ### end Alembic commands ###
