"""create_temperature_model

Revision ID: 3f4082b6f747
Revises: 199e08a1df5a
Create Date: 2024-05-03 20:51:25.618562

"""

# revision identifiers, used by Alembic.
revision = "3f4082b6f747"
down_revision = "199e08a1df5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
