"""create_temperature_model

Revision ID: 199e08a1df5a
Revises: efcab057508e
Create Date: 2024-05-03 20:47:41.307269

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "199e08a1df5a"
down_revision = "efcab057508e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temperature",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("temperature", sa.String(length=10), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperature")
    # ### end Alembic commands ###
